controller_list:
  - name: fake_irb120_cup_controller
    joints:
      - irb120_joint_1
      - irb120_joint_2
      - irb120_joint_3
      - irb120_joint_4
      - irb120_joint_5
      - irb120_joint_6
  - name: fake_irb120_plate_controller
    joints:
      - irb120_joint_1
      - irb120_joint_2
      - irb120_joint_3
      - irb120_joint_4
      - irb120_joint_5
      - irb120_joint_6
initial:  # Define initial robot poses.
  - group: irb120_cup
    pose: zero_pose
  - group: irb120_plate
    pose: zero_pose